"""empty message

Revision ID: 0707ea2c1e21
Revises: 27e11505b8f0
Create Date: 2023-05-24 23:24:24.466408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0707ea2c1e21'
down_revision = '27e11505b8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=False))
        batch_op.drop_column('adress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
