"""empty message

Revision ID: 0ac9e52913a7
Revises: 0707ea2c1e21
Create Date: 2023-06-19 23:04:32.908639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac9e52913a7'
down_revision = '0707ea2c1e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=480), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piso', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
